### ISSUE TITLE
"region" is undefined (missing part)

### ISSUE THREAD

**Issue by leamarty** [AdamMagaluk/statsd-cloudwatch#2]
Hi! So, there's an error in this line:
https://github.com/AdamMagaluk/statsd-cloudwatch/blob/master/backends/statsd-cloudwatch-backend/lib/init.js#L41

``` js
function getRegion(options, callback) {
  if (options.region) {
    return callback(null, region);
  }
  ...
}
```

The problem is that "region" doesn't exist! It should be `options.region`

Would you please fix it?

Should be:

``` js
function getRegion(options, callback) {
  if (options.region) {
    return callback(null, options.region);
  }
  ...
}
```

Thank you! And thanks for the project, works great (after that change :smile:  )

**Comment by AdamMagaluk** [comment]
Fixed in https://github.com/AdamMagaluk/statsd-cloudwatch/commit/78b741bf7c1621a7bdd6433b43624f41292557f3

Also note not much more development is gonna go into this besides obvious simple errors. You might want to take a look at [Telegraf](https://github.com/influxdata/telegraf) for statsd ingestion into Cloudwatch. They have a [Cloudwatch output plugin](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/cloudwatch) and a [statsd input collector](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd) that also adds dimensional data just like this project.

**Comment by leamarty** [comment]
Hey @AdamMagaluk thanks for your fix!

Actually I asked for this change because I was hoping that it will have an impact on this docker image:
https://hub.docker.com/r/adammagaluk/statsd-cloudwatch/

But I see that they are not linked to each other :cry: 

I already have statsd running with cloudwatch in production. I just wanted a docker image for statsd with cloudwatch (thats exactly what yours is, but it was useless for me because of that little bug). I will try to fork and do it myself.

Thanks anyway! :smile:

**Comment by AdamMagaluk** [comment]
Docker image updated. Forgot it wasn't on autobuild.
